import React, { useState, useEffect } from 'react';
// Importing icons from Lucide React
import { Book, Search, MessageSquare, Repeat, PenTool, Users, Lightbulb } from 'lucide-react'; // Added Lightbulb icon for prompts

// Data for the flashcards, now with grade-differentiated examples and sample prompts
const flashcardData = [
    {
        activityType: "1. Acquisition",
        description: "Learners listen, read, or watch to grasp concepts. This involves receiving information.",
        teacherActivities: {
            preK3: {
                text: "Generate simple stories with repetitive elements for early readers; create printable coloring pages that introduce new vocabulary; produce short, engaging audio clips for listening comprehension, **with varied voices to aid auditory processing (desirable difficulty)**.",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To help my Pre-K to 3rd graders recognize sight words']. **Action**: Generate a simple story with repetitive elements. **Purpose**: To help Pre-K to 3rd graders learn [NEW_VOCABULARY_WORD] and **practice retrieval**. **Expectation**: The story should be about [TOPIC], feature [CHARACTER_TYPE], be no more than [NUMBER] sentences long, and ask [NUMBER] simple retrieval questions about the story's events. Highlight the repetitive phrase."
            },
            grade4_6: {
                text: "Generate summaries of historical events or science topics at a 4-6 grade reading level; design interactive quizzes with picture-based answers; develop scripts for short educational puppet shows. **Intersperse quizzes within longer summaries to encourage active processing (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To help my 4th-6th graders understand basic scientific processes']. **Action**: Summarize the historical event. **Purpose**: To help 4th-6th graders understand [HISTORICAL_EVENT] and **improve retention through spaced practice**. **Expectation**: The summary should be at a 4th-6th grade reading level, cover [KEY_POINTS], be around [NUMBER] paragraphs. Include [NUMBER] multiple-choice quiz questions with image suggestions, placed every [NUMBER] paragraphs to break up the reading."
            },
            grade7_10: {
                text: "Generate concise summaries of complex literary texts or scientific articles; create differentiated reading passages at various levels of complexity for a given topic; design interactive quizzes with automated feedback focusing on factual recall and comprehension. **Vary the format of generated summaries (e.g., bullet points, narrative, concept map outlines) to encourage flexible thinking (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To enhance my 7th-10th graders' ability to synthesize information from complex texts']. **Action**: Generate a concise summary. **Purpose**: To help 7th-10th graders grasp the main concepts of [SCIENTIFIC_ARTICLE_TITLE/LITERARY_TEXT] and **enhance understanding through varied encoding**. **Expectation**: The summary should be no more than [NUMBER] words, highlighting [MAIN_ARGUMENT/KEY_FINDINGS]. Provide [NUMBER] versions: one bulleted, one narrative, and one as a concept map outline. Also, provide [NUMBER] differentiated reading passages from this summary at a [READING_LEVEL] and [READING_LEVEL] complexity."
            },
            grade11_12: {
                text: "Generate detailed synopses of academic papers or dense historical documents; create sophisticated reading passages with advanced vocabulary for specific subjects; develop video scripts for in-depth instructional content (e.g., advanced physics concepts, economic theories); produce realistic, multi-faceted case studies for high-level analysis. **Introduce subtle inconsistencies or missing information in case studies to prompt deeper investigation and critical evaluation (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To foster critical evaluation skills in my 11th-12th graders']. **Action**: Develop a video script for instructional content. **Purpose**: To explain [ADVANCED_PHYSICS_CONCEPT/ECONOMIC_THEORY] to 11th-12th graders and **foster critical thinking**. **Expectation**: The script should be approximately [DURATION] minutes long, include explanations of [SUB_TOPICS], and incorporate visuals suggestions. Generate a realistic, multi-faceted case study related to this concept for analysis, including [NUMBER] subtle ambiguities or gaps that require students to infer or research further."
            }
        },
        studentInteractions: {
            preK3: {
                text: "Students can ask GenAI to tell a story about animals or a specific theme; use it to learn new simple words with definitions and pictures; ask for 'what comes next' in a simple sequence. **GenAI can occasionally introduce a new, slightly more complex word to gently expand vocabulary (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To learn new animal vocabulary words']. **Action**: Tell me a story. **Purpose**: To help me learn about [ANIMAL_TYPE/THEME] and **expand my vocabulary**. **Expectation**: The story should be short and have pictures to help me understand new words like [WORD_1], [WORD_2]. Occasionally introduce one new word slightly above my current level and explain it with simple context."
            },
            grade4_6: {
                text: "Students can ask GenAI to explain concepts like 'photosynthesis' in simpler terms; summarize short articles about animals or planets; generate practice questions on multiplication or grammar rules. **GenAI can provide questions that require retrieval from earlier parts of the explanation (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To understand how plants make food']. **Action**: Explain [CONCEPT_NAME] to me. **Purpose**: To help me understand it easily and **practice active recall**. **Expectation**: Explain it like I'm in [GRADE_LEVEL], using simple words and giving [NUMBER] examples related to [TOPIC]. After the explanation, ask me [NUMBER] questions that require me to remember key details without looking back immediately."
            },
            grade7_10: {
                text: "Students can ask GenAI to explain concepts in simpler terms or from different angles; summarize long articles or chapters; generate practice questions on a topic with hints; create flashcards for vocabulary or key facts; or produce alternative explanations for difficult mathematical or scientific material. **GenAI can present concepts from a slightly different perspective after the initial explanation to encourage deeper processing (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To prepare for my upcoming science test']. **Action**: Generate practice questions. **Purpose**: To help me study for my [SUBJECT] test on [TOPIC] and **improve long-term retention**. **Expectation**: Provide [NUMBER] multiple-choice questions with hints, and then give me the answers at the end. After I answer, provide an alternative explanation of the concept from a slightly different angle to reinforce learning. Focus on [SPECIFIC_AREA_OF_TOPIC]."
            },
            grade11_12: {
                text: "Students can ask GenAI for deeper explanations of abstract concepts; request detailed summaries of research papers or complex theories; generate advanced practice problems (e.g., calculus, organic chemistry) with step-by-step solutions; create comprehensive digital flashcards with complex definitions and examples; or use it to explore different theoretical frameworks for a given topic. **GenAI can provide related but distinct problems (interleaved practice) to prevent rote memorization (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To grasp the nuances of quantum mechanics']. **Action**: Explain [ABSTRACT_CONCEPT/THEORY] in depth. **Purpose**: To provide a comprehensive understanding for my [CLASS_NAME] assignment and **strengthen my problem-solving skills**. **Expectation**: Explain the concept from [PERSPECTIVE_1] and [PERSPECTIVE_2], discuss its implications in [FIELD_1] and [FIELD_2]. Offer [NUMBER] detailed examples to illustrate its application, then provide [NUMBER] interleaved practice problems that require applying this concept along with [RELATED_CONCEPT_1] and [RELATED_CONCEPT_2]."
            }
        },
        humanAiHumanTip: "Human-AI-Human Tip: Teachers define learning goals (Human), GenAI generates varied resources (AI), and students critically evaluate, select, and discuss content (Human)." ,
        icon: <Book className="text-violet-500 mb-3" size={48} />
    },
    {
        activityType: "2. Investigation",
        description: "Learners explore, question, and research, often to solve problems or understand phenomena. This involves active inquiry.",
        teacherActivities: {
            preK3: {
                text: "Create simple 'mystery boxes' with clues for students to guess an object; generate 'what if' scenarios about animal habitats; design scavenger hunts for colors or shapes around the classroom. **GenAI can generate 'mystery' elements that require simple inference rather than direct fact recall (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To encourage my Pre-K to 3rd graders to ask scientific questions']. **Action**: Generate 'what if' scenarios. **Purpose**: To spark curiosity in Pre-K to 3rd graders about [ANIMAL_HABITAT] and **encourage inferential thinking**. **Expectation**: Create [NUMBER] simple scenarios, like 'What if [ANIMAL] lived in [UNUSUAL_PLACE]?' Each scenario should have a simple question for discussion that requires students to make a logical guess based on the 'what if'."
            },
            grade4_6: {
                text: "Generate open-ended research prompts about local ecosystems or historical figures; create simplified hypothetical scenarios or datasets about weather patterns or animal migration for students to analyze; design simple 'detective' games requiring students to gather information. **GenAI can provide slightly ambiguous initial information in scenarios, requiring students to ask clarifying questions (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To develop research skills in my 4th-6th graders']. **Action**: Generate open-ended research prompts. **Purpose**: To guide 4th-6th graders in investigating [LOCAL_ECOSYSTEM/HISTORICAL_FIGURE] and **promote critical questioning**. **Expectation**: Provide [NUMBER] prompts that encourage research beyond simple facts, focusing on 'how' or 'why'. Suggest simple resources for them to explore. For one scenario, include a piece of information that is slightly incomplete or vague, prompting students to ask clarifying questions."
            },
            grade7_10: {
                text: "Curate diverse digital resources (articles, basic datasets, simple simulations) tailored to a specific inquiry question (e.g., 'What factors influence climate?'); generate open-ended research prompts requiring data collection and analysis; create hypothetical scenarios or datasets for students to analyze (e.g., analyzing population trends, scientific experiment results); or design escape rooms/puzzles that require investigation and problem-solving to solve. **GenAI can present slightly contradictory 'expert' opinions in a scenario to encourage source evaluation (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To improve data analysis and evaluation in my 7th-10th graders']. **Action**: Generate hypothetical scenarios. **Purpose**: To help 7th-10th graders analyze [TOPIC_AREA_E.G._POPULATION_TRENDS] and **develop critical evaluation skills**. **Expectation**: Create [NUMBER] detailed scenarios, each with a small dataset or set of variables. Include questions that require students to analyze trends and make predictions based on the provided data. For one scenario, include two brief 'expert' statements that are subtly contradictory, requiring students to identify the conflict and propose a resolution."
            },
            grade11_12: {
                text: "Curate extensive and diverse resources (peer-reviewed articles, complex datasets, advanced simulations) for in-depth inquiry (e.g., 'Analyzing the socio-economic impacts of climate change'); generate complex, multi-faceted research prompts requiring critical evaluation of sources; create intricate hypothetical scenarios or large-scale datasets for students to rigorously analyze and draw conclusions; or design elaborate digital 'cold case' simulations requiring advanced investigative techniques. **GenAI can introduce irrelevant or distracting information into resource sets to train information filtering (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To enhance advanced investigative and information filtering skills']. **Action**: Design an elaborate digital 'cold case' simulation. **Purpose**: To engage 11th-12th graders in advanced investigative techniques for [HISTORICAL_EVENT/SCIENTIFIC_MYSTERY] and **train information filtering**. **Expectation**: Create a narrative with [NUMBER] key 'clues' (e.g., historical documents, scientific data snippets). The simulation should require students to synthesize information, formulate hypotheses, and justify their conclusions based on the evidence. Include [NUMBER] pieces of information that are plausible but ultimately irrelevant to the core mystery, requiring students to discern key data."
            }
        },
        studentInteractions: {
            preK3: {
                text: "Students can ask GenAI to suggest things to find in the classroom; ask 'why' questions about simple observations; get ideas for what to build with blocks. **GenAI can pose a 'why' question after an observation, encouraging simple causal thinking (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To understand why things happen in nature']. **Action**: Ask me 'why' questions about observations. **Purpose**: To help me think about [SIMPLE_OBSERVATION, E.G._WHY_DO_LEAVES_FALL]. **Expectation**: Ask me [NUMBER] 'why' questions about common things I see, and then give a simple answer after I try."
            },
            grade4_6: {
                text: "Students can use GenAI to brainstorm simple research questions like 'How do plants grow?'; find basic facts about historical events; generate ideas for science fair projects; simulate simple scenarios like 'What if the sun disappeared?'. **GenAI can prompt students to justify their initial assumptions in simulations (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To explore scientific concepts through predictions']. **Action**: Simulate a simple scenario. **Purpose**: To help me understand [CONCEPT_NAME] through active prediction. **Expectation**: Simulate 'What if the sun disappeared?'. Before revealing the outcome, ask me to predict [NUMBER] things that would happen and explain why I think so."
            },
            grade7_10: {
                text: "Students can use GenAI to brainstorm research questions for a science project or history report; find diverse perspectives on a current event; generate hypotheses for scientific experiments; simulate basic scenarios (e.g., 'What if we double the population?'); analyze small datasets (by asking GenAI to process and summarize key trends); or practice critical thinking by challenging GenAI's initial answers or suggesting alternative interpretations. **GenAI can offer a critique of a student's initial hypothesis, prompting refinement (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To formulate strong scientific hypotheses']. **Action**: Generate hypotheses for an experiment. **Purpose**: To help me design an experiment on [SCIENTIFIC_TOPIC]. **Expectation**: Provide [NUMBER] testable hypotheses related to [DEPENDENT_VARIABLE] and [INDEPENDENT_VARIABLE]. After I propose my own hypothesis, provide a constructive critique pointing out a potential flaw or area for refinement, and suggest [NUMBER] ways to collect data for each."
            },
            grade11_12: {
                text: "Students can use GenAI to refine complex research questions for dissertations or capstone projects; find nuanced, academic perspectives on contentious issues; generate sophisticated hypotheses for advanced research; run complex simulations (e.g., economic models, biological systems); process and interpret large, multivariate datasets; or engage in advanced critical thinking by debating GenAI's conclusions and exploring logical fallacies. **GenAI can intentionally introduce a common logical fallacy into a simulated debate point, requiring the student to identify and refute it (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To refine my research questions and identify logical fallacies']. **Action**: Refine my research question. **Purpose**: To make my capstone project question on [BROAD_TOPIC] more focused and academic and **to identify logical fallacies**. **Expectation**: Review my current question: '[YOUR_CURRENT_QUESTION]'. Suggest [NUMBER] ways to narrow its scope, add academic rigor, and make it more suitable for a [TYPE_OF_PROJECT_E.G._DISSERTATION]. In our simulated debate, introduce [NUMBER] arguments that contain a common logical fallacy (e.g., straw man, ad hominem) for me to identify and refute."
            }
        },
        humanAiHumanTip: "Human-AI-Human Tip: Teachers pose open-ended problems (Human), GenAI helps explore possibilities and gather initial data (AI), and students analyze, synthesize, and present findings (Human)." ,
        icon: <Search className="text-violet-500 mb-3" size={48} />
    },
    {
        activityType: "3. Discussion",
        description: "Learners articulate their understanding, challenge ideas, and engage in dialogue with peers or the teacher. This fosters collaborative meaning-making.",
        teacherActivities: {
            preK3: {
                text: "Generate simple prompts for 'show and tell'; create scenarios for sharing toys; suggest sentence starters for polite disagreements ('I hear you, but I think...'). **GenAI can generate prompts that require students to listen to a peer's idea and then add a related, but different, thought (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To foster polite classroom discussions']. **Action**: Generate simple prompts. **Purpose**: To encourage 'show and tell' discussions for Pre-K to 3rd graders and **promote active listening**. **Expectation**: Provide [NUMBER] prompts that are easy to understand. For each prompt, include a follow-up instruction like 'After [PEER_NAME] shares, tell us something similar or different you think about their object'."
            },
            grade4_6: {
                text: "Generate discussion prompts for classroom debates on topics like 'Should we have school uniforms?'; create simple character personas for role-playing a historical event; simulate a friendly argument about a book's ending. **GenAI can provide slightly incomplete arguments for personas, requiring students to fill in the gaps with their own reasoning (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To develop respectful debate skills in my 4th-6th graders']. **Action**: Generate discussion prompts. **Purpose**: To facilitate a classroom debate for 4th-6th graders on [DEBATE_TOPIC] and **develop argumentative skills**. **Expectation**: Provide [NUMBER] prompts that cover both sides of the argument and encourage students to use evidence. Also, create [NUMBER] simple character personas related to the topic for role-playing, where each persona's argument has one missing logical step for students to complete."
            },
            grade7_10: {
                text: "Generate thought-provoking discussion prompts for debates or small group work on controversial topics (e.g., ethical dilemmas in science, historical interpretations); create detailed personas for role-playing discussions (e.g., historical figures, different scientific viewpoints, characters from literature); simulate a short, guided conversation on a specific topic for students to analyze; or provide balanced counter-arguments for students to critically evaluate and refute. **GenAI can simulate a peer's argument that contains a common misconception, prompting students to identify and correct it (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To improve critical reasoning and discussion in my 7th-10th graders']. **Action**: Generate detailed personas for role-playing discussion. **Purpose**: To facilitate a rich discussion among 7th-10th graders on [CONTROVERSIAL_TOPIC] and **hone critical reasoning**. **Expectation**: Create [NUMBER] personas, each with a distinct viewpoint and background. Provide talking points for each. In one persona's talking points, include a common misconception related to the topic for students to identify and politely correct during the discussion."
            },
            grade11_12: {
                text: "Generate complex discussion prompts requiring nuanced argumentation for Socratic seminars or advanced debates (e.g., philosophical concepts, policy implications); create intricate personas with specific motivations and backstories for in-depth role-playing (e.g., UN delegates, legal teams); simulate extended, multi-turn discussions on highly controversial or abstract topics for students to dissect; or provide sophisticated, well-reasoned counter-arguments to push students' critical thinking and rebuttal skills. **GenAI can introduce unexpected data or ethical dilemmas during a simulated discussion to force real-time adaptation of arguments (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To prepare my 11th-12th graders for advanced academic discussions']. **Action**: Generate complex discussion prompts. **Purpose**: To prepare for a Socratic seminar with 11th-12th graders on [PHILOSOPHICAL_CONCEPT/POLICY_IMPLICATION] and **promote adaptive argumentation**. **Expectation**: Provide [NUMBER] open-ended questions that encourage nuanced argumentation and critical thinking. Include questions that explore ethical dimensions and real-world relevance. During a simulated discussion, unexpectedly introduce a new piece of data or an unforeseen ethical dilemma that requires students to adapt their initial arguments."
            }
        },
        studentInteractions: {
            preK3: {
                text: "Students can ask GenAI for ideas to talk about with a friend; practice telling a story to GenAI; get suggestions for how to share with others. **GenAI can prompt the student to retell a story in their own words after hearing it, encouraging recall (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To improve my storytelling skills']. **Action**: Tell me a story. **Purpose**: To help me practice telling stories. **Expectation**: Tell me a short story about [TOPIC], then ask me to tell it back to you in my own words. Give me feedback on how well I remembered the main parts."
            },
            grade4_6: {
                text: "Students can engage GenAI in a simple debate about their favorite animal; ask for different opinions on a story character; practice explaining a science concept to GenAI. **GenAI can ask 'why' questions about the student's opinions to encourage justification (desirable difficulty).**",
                prompt: "**My Learning Goal is**: [Clearly state your learning objective, e.g., 'To practice arguing politely']. **Action**: Have a simple debate with me. **Purpose**: To practice my arguing skills about [FAVORITE_ANIMAL/TOPIC] and **justify my reasoning**. **Expectation**: Argue against my choice, giving me [NUMBER] reasons why [OPPOSITE_VIEW] is better. After I give my response, ask me 'Why do you think that?' or 'Can you give me an example?'"
            },
            grade7_10: {
                text: "Students can engage GenAI as a debate partner on a specific topic, receiving basic counter-arguments; ask for multiple perspectives on a social issue or historical event; receive instant feedback on the clarity and coherence of their arguments; practice articulating their thoughts and structuring responses before a real discussion; or use it to explore different sides of a complex is
